build: off

install:
  - node --version
  - npm --version
  - ps: Install-Product node 7.4.0 x64
  - npm install -g npm --silent
  - node --version
  - npm --version

test_script:
  - npm install
  - npm run test
